name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main
    paths:
      - 'docnest_backend/**'
      - '.github/workflows/**'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: docnest-backend
  ECS_SERVICE: docnest-ecs-service
  ECS_CLUSTER: docnest-cluster
  ECS_TASK_DEFINITION: docnest-backend-td
  CONTAINER_NAME: docnest-container

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Check AWS credentials
      run: |
        if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ] || [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
          echo "AWS credentials are not set in repository secrets"
          exit 1
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Verify AWS credentials
      run: aws sts get-caller-identity

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Create .env file
      run: |
        cd docnest_backend
        touch .env
        for secret in POSTGRES_SERVER POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB JWT_SECRET_KEY GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_BUCKET_NAME; do
          if [ -z "${{ secrets[secret] }}" ]; then
            echo "Secret $secret is not set"
            exit 1
          fi
          echo "$secret=${{ secrets[secret] }}" >> .env
        done
        echo "AWS_REGION=${{ env.AWS_REGION }}" >> .env

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd docnest_backend
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        if [ $? -ne 0 ]; then
          echo "Docker build failed"
          exit 1
        fi
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        if [ $? -ne 0 ]; then
          echo "Docker push failed"
          exit 1
        fi
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} \
        --query taskDefinition > task-definition.json
        if [ $? -ne 0 ]; then
          echo "Failed to download task definition"
          exit 1
        fi

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true